# Generated by Django 4.2.23 on 2025-08-15 19:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Titre du document"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="documents/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "pdf",
                                    "doc",
                                    "docx",
                                    "xls",
                                    "xlsx",
                                    "ppt",
                                    "pptx",
                                    "txt",
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "gif",
                                    "zip",
                                    "rar",
                                ]
                            )
                        ],
                        verbose_name="Fichier",
                    ),
                ),
                (
                    "file_name",
                    models.CharField(
                        max_length=255, verbose_name="Nom du fichier original"
                    ),
                ),
                (
                    "file_size",
                    models.BigIntegerField(verbose_name="Taille du fichier (bytes)"),
                ),
                (
                    "mime_type",
                    models.CharField(max_length=100, verbose_name="Type MIME"),
                ),
                (
                    "s3_bucket",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Bucket S3"
                    ),
                ),
                (
                    "s3_key",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="Clé S3"
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public - Visible par le client"),
                            (
                                "internal",
                                "Interne - Visible par l'équipe NOURX seulement",
                            ),
                            ("restricted", "Restreint - Accès limité"),
                        ],
                        default="public",
                        max_length=15,
                        verbose_name="Visibilité",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        default="1.0", max_length=20, verbose_name="Version"
                    ),
                ),
                (
                    "version_status",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("review", "En révision"),
                            ("approved", "Approuvé"),
                            ("archived", "Archivé"),
                        ],
                        default="draft",
                        max_length=15,
                        verbose_name="Statut de la version",
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="Tags séparés par des virgules",
                        max_length=200,
                        null=True,
                        verbose_name="Tags",
                    ),
                ),
                (
                    "download_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre de téléchargements"
                    ),
                ),
                (
                    "last_downloaded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Dernier téléchargement"
                    ),
                ),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentFolder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nom du dossier"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Ordre")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subfolders",
                        to="documents.documentfolder",
                        verbose_name="Dossier parent",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_folders",
                        to="projects.project",
                        verbose_name="Projet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dossier de documents",
                "verbose_name_plural": "Dossiers de documents",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="DocumentAccess",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("view", "Consultation"),
                            ("download", "Téléchargement"),
                            ("share", "Partage"),
                            ("delete", "Suppression"),
                        ],
                        max_length=10,
                        verbose_name="Action",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Adresse IP"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, null=True, verbose_name="User Agent"),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_logs",
                        to="documents.document",
                        verbose_name="Document",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="document_accesses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Accès document",
                "verbose_name_plural": "Accès documents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="document",
            name="folder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="documents.documentfolder",
                verbose_name="Dossier",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="previous_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="newer_versions",
                to="documents.document",
                verbose_name="Version précédente",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="projects.project",
                verbose_name="Projet",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="uploaded_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploaded_documents",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Téléchargé par",
            ),
        ),
        migrations.AddIndex(
            model_name="documentfolder",
            index=models.Index(
                fields=["project"], name="documents_d_project_50480f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentfolder",
            index=models.Index(
                fields=["parent"], name="documents_d_parent__408df5_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="documentfolder",
            unique_together={("project", "parent", "name")},
        ),
        migrations.AddIndex(
            model_name="documentaccess",
            index=models.Index(
                fields=["document", "created_at"], name="documents_d_documen_98b2fa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentaccess",
            index=models.Index(
                fields=["user", "action"], name="documents_d_user_id_d0e978_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentaccess",
            index=models.Index(
                fields=["action", "created_at"], name="documents_d_action_901633_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["project", "visibility"], name="documents_d_project_9fa4ef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["folder"], name="documents_d_folder__b9ba49_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["uploaded_by"], name="documents_d_uploade_6455fb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["version_status"], name="documents_d_version_e0ecdb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["mime_type"], name="documents_d_mime_ty_29cc61_idx"
            ),
        ),
    ]
