# Generated by Django 4.2.23 on 2025-08-15 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Nom du client"),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Email principal"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Téléphone"
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="Adresse"),
                ),
                (
                    "main_contact_name",
                    models.CharField(
                        max_length=100, verbose_name="Nom du contact principal"
                    ),
                ),
                (
                    "main_contact_email",
                    models.EmailField(
                        max_length=254, verbose_name="Email du contact principal"
                    ),
                ),
                (
                    "main_contact_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "industry",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Secteur d'activité",
                    ),
                ),
                (
                    "company_size",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1-10", "1-10 employés"),
                            ("11-50", "11-50 employés"),
                            ("51-200", "51-200 employés"),
                            ("200+", "Plus de 200 employés"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="Taille de l'entreprise",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("prospect", "Prospect"),
                            ("active", "Client actif"),
                            ("inactive", "Client inactif"),
                            ("archived", "Archivé"),
                        ],
                        default="prospect",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="Notes internes"
                    ),
                ),
            ],
            options={
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ClientMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Propriétaire"),
                            ("admin", "Administrateur"),
                            ("member", "Membre"),
                            ("viewer", "Lecteur seul"),
                        ],
                        default="member",
                        max_length=10,
                        verbose_name="Rôle",
                    ),
                ),
                (
                    "can_view_billing",
                    models.BooleanField(
                        default=False, verbose_name="Peut voir la facturation"
                    ),
                ),
                (
                    "can_manage_team",
                    models.BooleanField(
                        default=False, verbose_name="Peut gérer l'équipe"
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="clients.client",
                        verbose_name="Client",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_memberships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Membre client",
                "verbose_name_plural": "Membres clients",
            },
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(fields=["status"], name="clients_cli_status_ce0d15_idx"),
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(fields=["name"], name="clients_cli_name_5ab7bc_idx"),
        ),
        migrations.AddIndex(
            model_name="clientmember",
            index=models.Index(
                fields=["user", "client"], name="clients_cli_user_id_9462b3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clientmember",
            index=models.Index(fields=["role"], name="clients_cli_role_71f673_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="clientmember",
            unique_together={("user", "client")},
        ),
    ]
