services:
  db:
    image: postgres:15-alpine
    container_name: nourx-db
    environment:
      POSTGRES_DB: nourx
      POSTGRES_USER: nourx_user
      POSTGRES_PASSWORD: nourx_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=en_US.UTF-8 --lc-ctype=en_US.UTF-8"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nourx_user -d nourx"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
