# Generated by Django 4.2.23 on 2025-08-15 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clients", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLogArchive",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archive_date", models.DateField(verbose_name="Date d'archivage")),
                (
                    "logs_count",
                    models.PositiveIntegerField(verbose_name="Nombre de logs"),
                ),
                ("from_date", models.DateTimeField(verbose_name="Période du")),
                ("to_date", models.DateTimeField(verbose_name="Période au")),
                (
                    "compressed_data",
                    models.BinaryField(verbose_name="Données compressées"),
                ),
                (
                    "compression_ratio",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Ratio de compression"
                    ),
                ),
                (
                    "checksum",
                    models.CharField(
                        max_length=64, verbose_name="Somme de contrôle SHA-256"
                    ),
                ),
            ],
            options={
                "verbose_name": "Archive de logs d'audit",
                "verbose_name_plural": "Archives de logs d'audit",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["archive_date"], name="audit_audit_archive_530125_idx"
                    ),
                    models.Index(
                        fields=["from_date", "to_date"],
                        name="audit_audit_from_da_318e48_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Création"),
                            ("update", "Modification"),
                            ("delete", "Suppression"),
                            ("login", "Connexion"),
                            ("logout", "Déconnexion"),
                            ("view", "Consultation"),
                            ("download", "Téléchargement"),
                            ("export", "Export"),
                            ("import", "Import"),
                            ("send", "Envoi"),
                            ("approve", "Approbation"),
                            ("reject", "Rejet"),
                            ("archive", "Archivage"),
                            ("restore", "Restauration"),
                            ("payment", "Paiement"),
                            ("refund", "Remboursement"),
                            ("other", "Autre"),
                        ],
                        max_length=20,
                        verbose_name="Action",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="Description"),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("info", "Information"),
                            ("warning", "Avertissement"),
                            ("error", "Erreur"),
                            ("critical", "Critique"),
                        ],
                        default="info",
                        max_length=10,
                        verbose_name="Niveau",
                    ),
                ),
                (
                    "object_id",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="ID de l'objet",
                    ),
                ),
                (
                    "old_values",
                    models.JSONField(
                        blank=True,
                        help_text="État avant la modification",
                        null=True,
                        verbose_name="Valeurs avant",
                    ),
                ),
                (
                    "new_values",
                    models.JSONField(
                        blank=True,
                        help_text="État après la modification",
                        null=True,
                        verbose_name="Nouvelles valeurs",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Adresse IP"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, null=True, verbose_name="User Agent"),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True,
                        max_length=40,
                        null=True,
                        verbose_name="Clé de session",
                    ),
                ),
                (
                    "extra_data",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Données supplémentaires"
                    ),
                ),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        help_text="Identifiant pour grouper plusieurs actions liées",
                        max_length=36,
                        null=True,
                        verbose_name="ID de batch",
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Acteur",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="clients.client",
                        verbose_name="Client concerné",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                        verbose_name="Type d'objet",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="projects.project",
                        verbose_name="Projet concerné",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log d'audit",
                "verbose_name_plural": "Logs d'audit",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["actor", "created_at"],
                        name="audit_audit_actor_i_ec0f72_idx",
                    ),
                    models.Index(
                        fields=["action", "created_at"],
                        name="audit_audit_action_766c6d_idx",
                    ),
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="audit_audit_content_4c2ead_idx",
                    ),
                    models.Index(
                        fields=["client", "created_at"],
                        name="audit_audit_client__8dabcb_idx",
                    ),
                    models.Index(
                        fields=["project", "created_at"],
                        name="audit_audit_project_3490cc_idx",
                    ),
                    models.Index(
                        fields=["level", "created_at"],
                        name="audit_audit_level_7254c2_idx",
                    ),
                    models.Index(
                        fields=["batch_id"], name="audit_audit_batch_i_982e87_idx"
                    ),
                    models.Index(
                        fields=["ip_address"], name="audit_audit_ip_addr_685e3f_idx"
                    ),
                ],
            },
        ),
    ]
